export const SET_POKEMONS = "SET_POKEMONS"
export const SET_LOADING = 'SET_LOADING'
export const SET_FAVORITE = 'SET_FAVORITE'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_FAVORITES_POKEMONS = 'SET_FAVORITES_POKEMONS'
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE'